AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  crc-backend

  Sample SAM Template for crc-backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON

  Api:
    Cors: 
      AllowMethods: "'POST'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'*'"

Resources:
  GetVisitCountsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: get_visit_counts/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Events:
        GetVisitCounts:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /visitcounts
            Method: post
      Policies:
        - AmazonDynamoDBFullAccess:
            TableName: arn:aws:dynamodb:us-east-1:767397845715:table/apps-visit-counts
  
  # MyDynamoDBAccessPolicy:
  #   Type: AWS::IAM::ManagedPolicy
  #   Properties:
  #     PolicyDocument:
  #       Version: "2012-10-17"
  #       Statement:
  #         - Effect: Allow
  #           Action:
  #             - dynamodb:GetItem
  #             - dynamodb:PutItem
  #           Resource: arn:aws:dynamodb:us-east-1:767397845715:table/apps-visit-counts
      

Outputs:
  GetVisitCountsFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for GetVisitCounts function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/visitcounts/"
  GetVisitCountsFunction:
    Description: "GetVisitCounts Lambda Function ARN"
    Value: !GetAtt GetVisitCountsFunction.Arn
  GetVisitCountsFunctionIamRole:
    Description: "Implicit IAM Role created for GetVisitCounts function"
    Value: !GetAtt GetVisitCountsFunction.Arn